import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import type { ImportError, User } from "./types";

export function AdminView() {
  const [accounts,setAccounts]=useState<User[]>([]); const [notice,setNotice]=useState(""); const [errors,setErrors]=useState<ImportError[]>([]);
  const refresh=()=>api.getManagedUsers().then(setAccounts); useEffect(()=>{void refresh()},[]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.createParent(String(f.get("name")),String(f.get("username")),String(f.get("password")));e.currentTarget.reset();setNotice("Parent account created.");await refresh()}catch(x){setNotice(x instanceof Error?x.message:"Could not create account")}};
  const reset=async(user:User)=>{const password=window.prompt(`New password for ${user.display_name} (8+ characters)`);if(!password)return;try{await api.adminReset(user.id,password);setNotice("Password reset. Existing login tokens for this account are now invalid.")}catch(x){setNotice(x instanceof Error?x.message:"Could not reset")}};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setErrors([]);try{const doc=JSON.parse(await file.text());const result=await api.importQuestions(doc);setNotice(`Imported ${result.templates_imported} templates for ${result.subject}.`)}catch(x){setNotice(x instanceof Error?x.message:"Import failed");setErrors((x as Error&{details?:ImportError[]}).details??[{path:"$",message:"The file is not valid JSON.",suggestion:"Check commas, quotes, and brackets, then try again."}])}e.target.value=""};
  return <main className="portal-page"><header className="portal-hero"><div><p className="eyebrow">Administration</p><h1>People &amp; question banks</h1><p>Create parent access, help families regain access, and safely validate reviewed content.</p></div></header>{notice&&<p className="notice" role="status">{notice}</p>}<div className="portal-grid"><section className="panel"><h2>Create a parent</h2><form onSubmit={create} className="stack-form"><label>Display name<input name="name" required/></label><label>Username<input name="username" minLength={3} required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><button className="primary">Create parent</button></form></section><section className="panel"><h2>Parent &amp; learner accounts</h2>{accounts.length===0?<p className="empty">No family accounts yet.</p>:<div className="account-list">{accounts.map(p=><div key={p.id}><span><strong>{p.display_name}</strong><small>{p.role} · @{p.username}</small></span><button className="quiet" onClick={()=>reset(p)}>Reset password</button></div>)}</div>}</section><section className="panel import-panel"><p className="eyebrow">Schema v2</p><h2>Import questions</h2><p className="panel-copy">Choose a JSON question bank. Rabbit validates every path against the normative schema and generates sample questions before importing it into this server process.</p><label className="file-drop">Choose JSON file<input type="file" accept="application/json,.json" onChange={upload}/></label>{errors.length>0&&<div className="validation-errors"><h3>What needs attention</h3>{errors.map((e,i)=><article key={i}><code>{e.path}</code><strong>{e.message}</strong><p>Potential fix: {e.suggestion}</p></article>)}</div>}</section></div></main>;
}
