import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import type { User } from "./types";
import { Achievement, RaceTrack } from "./LearnerView";

export function Landing({ onLogin, onSignup, onDemo }: { onLogin: () => void; onSignup: () => void; onDemo: () => void }) {
  return <main className="landing">
    <section className="landing-hero"><div><p className="eyebrow">A learning race powered by accuracy</p><h1>Race up the hill.<br/><em>Learn with every step.</em></h1><p>Rabbit takes a big hop for every correct answer. Tortoise keeps moving steadily. Beat your accuracy target to help Rabbit reach the trophy first!</p><div className="hero-actions"><button className="primary demo-cta" onClick={onSignup}>Create a free account ▶</button><button className="quiet login-link" onClick={onDemo}>Try the demo</button><button className="quiet login-link" onClick={onLogin}>Log in</button></div><small>Supportive feedback makes every answer useful—even when Rabbit needs a nap.</small></div>
      <div className="landing-workspace-preview"><span className="preview-label">Real workspace preview · Parent view in demo</span><Achievement answered={3} correct={2} total={5} compact /><RaceTrack answered={3} total={5} correct={2} wrong={1} target={70} sleeping={false} /><div className="lesson-progress"><div><span>Today&apos;s trail</span><strong>4 / 5</strong></div><i><b style={{ width: "60%" }} /></i></div><div className="landing-question-preview"><p className="eyebrow">Difficulty 2 · +10 EXP</p><strong>Choose your answer</strong><div><span>A</span><span className="selected">B</span><span>C</span><span>D</span></div></div></div>
    </section><section className="feature-row"><article><b>01</b><h2>Answer and race</h2><p>Correct answers send Rabbit farther up the hill while Tortoise stays slow and steady.</p></article><article><b>02</b><h2>Beat your target</h2><p>Families choose an accuracy goal, and progress stays visible throughout the race.</p></article><article><b>03</b><h2>Reach the trophy</h2><p>Every finished trail earns silver. A perfect score unlocks the gold trophy!</p></article></section>
    <section className="mascot-moments" aria-labelledby="mascot-moments-title"><div className="moments-copy"><p className="eyebrow">Meet the racers</p><h2 id="mascot-moments-title">Fast thinking meets steady effort.</h2><p>Rabbit celebrates strong answers, Tortoise shows the power of consistency, and both keep practice friendly and encouraging.</p></div><div className="moment-grid"><article><img src="/rabbit-thinking.png" alt="Rabbit thinking carefully"/><strong>Think it through</strong><span>Helpful hints</span></article><article><img src="/tortoise-steady.png" alt="Tortoise walking steadily"/><strong>Keep moving</strong><span>Steady progress</span></article><article className="moment-celebrate"><img src="/rabbit-excited.png" alt="Rabbit jumping with excitement"/><strong>Win the trophy</strong><span>Accuracy celebrations</span></article></div></section>
  </main>;
}

export function Login({ onSuccess, onBack }: { onSuccess: (user: User) => void; onBack: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const auth = await api.login(email, password); sessionStorage.setItem("rabbit_token", auth.access_token); onSuccess(auth.user); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not log in"); } finally { setBusy(false); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><button type="button" className="quiet back" onClick={onBack}>◀ Back home</button><img src="/rabbit-reading-logo.png" alt=""/><p className="eyebrow">Welcome back</p><h1>Log in</h1><p>Parents use their email address. Learners can use the username their parent created.</p><label>Email address or learner username<input type="text" inputMode="email" autoComplete="username" required minLength={3} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Logging in…" : "Log in ▶"}</button></form></main>;
}

export function Signup({ onBack, onLogin }: { onBack: () => void; onLogin: () => void }) {
  const [sent, setSent] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { await api.signup(String(data.get("email")), String(data.get("displayName"))); setSent(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create your account"); } finally { setBusy(false); } };
  if (sent) return <main className="auth-page"><section className="auth-card"><img src="/rabbit-encouraging.png" alt="Rabbit cheering"/><p className="eyebrow">Check your inbox</p><h1>Your activation link is on its way</h1><p>Use the private link in the email within 7 days. If it expires, you can sign up again as long as the email is still available.</p><button className="primary full" onClick={onLogin}>Go to login</button></section></main>;
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><button type="button" className="quiet back" onClick={onBack}>◀ Back home</button><img src="/rabbit-reading-logo.png" alt=""/><p className="eyebrow">Free parent account</p><h1>Start your family&apos;s trail</h1><p>We&apos;ll email you a temporary activation link before asking you to create a password.</p><label>Your name<input name="displayName" autoComplete="name" required maxLength={80}/></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={320}/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Sending link…" : "Email my activation link ▶"}</button></form></main>;
}

export function Activate({ token, onSuccess, onBack }: { token: string; onSuccess: (user: User) => void; onBack: () => void }) {
  const [details, setDetails] = useState<{ email: string; display_name: string } | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(true);
  useEffect(() => { api.inspectActivation(token).then(setDetails).catch(caught => setError(caught instanceof Error ? caught.message : "This link cannot be used")).finally(() => setBusy(false)); }, [token]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password")); if (password !== String(data.get("confirmPassword"))) { setError("Passwords do not match"); return; } setBusy(true); setError(""); try { const auth = await api.activate(token, password); sessionStorage.setItem("rabbit_token", auth.access_token); window.history.replaceState({}, "", window.location.pathname); onSuccess(auth.user); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not activate your account"); } finally { setBusy(false); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><button type="button" className="quiet back" onClick={onBack}>◀ Back to login</button><img src="/rabbit-reading-logo.png" alt=""/><p className="eyebrow">Email confirmed</p><h1>Create your password</h1>{details && <p>Welcome, {details.display_name}. Finish setting up <strong>{details.email}</strong>.</p>}{busy && !details && <p>Checking your activation link…</p>}{details && <><label>New password<input name="password" type="password" autoComplete="new-password" required minLength={8}/></label><label>Confirm password<input name="confirmPassword" type="password" autoComplete="new-password" required minLength={8}/></label></>}{error && <p className="form-error" role="alert">{error}</p>}{details && <button className="primary full" disabled={busy}>{busy ? "Activating…" : "Activate account ▶"}</button>}</form></main>;
}
