import { FormEvent, useState } from "react";
import { api } from "./api";
import type { User } from "./types";
import { RaceTrack } from "./LearnerView";

export function Landing({ onLogin, onDemo }: { onLogin: () => void; onDemo: () => void }) {
  return <main className="landing">
    <section className="landing-hero"><div><p className="eyebrow">A learning race powered by accuracy</p><h1>Race up the hill.<br/><em>Learn with every step.</em></h1><p>Rabbit takes a big hop for every correct answer. Tortoise keeps moving steadily. Beat your accuracy target to help Rabbit reach the trophy first!</p><div className="hero-actions"><button className="primary demo-cta" onClick={onDemo}>Try the free demo ▶</button><button className="quiet login-link" onClick={onLogin}>Log in</button></div><small>Supportive feedback makes every answer useful—even when Rabbit needs a nap.</small></div>
      <div className="landing-workspace-preview"><span className="preview-label">The real learner workspace</span><RaceTrack answered={3} total={5} correct={2} wrong={1} target={70} sleeping={false} /><div className="lesson-progress"><div><span>Today&apos;s trail</span><strong>4 / 5</strong></div><i><b style={{ width: "60%" }} /></i></div><div className="landing-question-preview"><p className="eyebrow">Difficulty 2 · +10 EXP</p><strong>Choose your answer</strong><div><span>A</span><span className="selected">B</span><span>C</span><span>D</span></div></div></div>
    </section><section className="feature-row"><article><b>01</b><h2>Answer and race</h2><p>Correct answers send Rabbit farther up the hill while Tortoise stays slow and steady.</p></article><article><b>02</b><h2>Beat your target</h2><p>Families choose an accuracy goal, and progress stays visible throughout the race.</p></article><article><b>03</b><h2>Reach the trophy</h2><p>Rabbit wins trophy points by beating the target. Every race offers another chance to grow.</p></article></section>
    <section className="mascot-moments" aria-labelledby="mascot-moments-title"><div className="moments-copy"><p className="eyebrow">Meet the racers</p><h2 id="mascot-moments-title">Fast thinking meets steady effort.</h2><p>Rabbit celebrates strong answers, Tortoise shows the power of consistency, and both keep practice friendly and encouraging.</p></div><div className="moment-grid"><article><img src="/rabbit-thinking.png" alt="Rabbit thinking carefully"/><strong>Think it through</strong><span>Helpful hints</span></article><article><img src="/tortoise-steady.png" alt="Tortoise walking steadily"/><strong>Keep moving</strong><span>Steady progress</span></article><article className="moment-celebrate"><img src="/rabbit-excited.png" alt="Rabbit jumping with excitement"/><strong>Win the trophy</strong><span>Accuracy celebrations</span></article></div></section>
  </main>;
}

export function Login({ onSuccess, onBack }: { onSuccess: (user: User) => void; onBack: () => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const auth = await api.login(username, password); sessionStorage.setItem("rabbit_token", auth.access_token); onSuccess(auth.user); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not log in"); } finally { setBusy(false); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><button type="button" className="quiet back" onClick={onBack}>◀ Back home</button><img src="/rabbit-reading-logo.png" alt=""/><p className="eyebrow">Welcome back</p><h1>Log in</h1><p>Your role takes you to the right learning space.</p><label>Username<input autoComplete="username" required minLength={3} value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Logging in…" : "Log in ▶"}</button></form></main>;
}
