import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import { AttemptHistory } from "./AttemptHistory";
import type { FamilyLearner, Reward, WorksheetTopic } from "./types";

export function ParentView({ refreshKey }: { refreshKey: number }) {
  const [learners,setLearners]=useState<FamilyLearner[]>([]); const [selectedId,setSelectedId]=useState(""); const [notice,setNotice]=useState("");
  const [topics,setTopics]=useState<WorksheetTopic[]>([]); const [topicKey,setTopicKey]=useState(""); const [questionCount,setQuestionCount]=useState(10); const [generating,setGenerating]=useState(false);
  const refresh=async()=>{const data=await api.getLearners();setLearners(data);setSelectedId(id=>data.some(x=>x.id===id)?id:data[0]?.id??"")};
  useEffect(()=>{void refresh();void api.getWorksheetTopics().then(data=>{setTopics(data);setTopicKey(current=>data.some(topic=>`${topic.subject}:${topic.id}`===current)?current:(data[0]?`${data[0].subject}:${data[0].id}`:""))}).catch(error=>setNotice(error instanceof Error?error.message:"Could not load worksheet topics"))},[refreshKey]); const selected=learners.find(x=>x.id===selectedId); const progress=selected?.progress; const [reward,setReward]=useState<Reward>({enabled:false,target_accuracy:80,reward:"A trip to the bookshop"});
  useEffect(()=>{if(progress)setReward(progress.reward)},[selectedId,progress?.points]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.createLearner(String(f.get("name")),String(f.get("username")),String(f.get("password")));e.currentTarget.reset();setNotice("Learner profile created.");await refresh()}catch(x){setNotice(x instanceof Error?x.message:"Could not create learner")}};
  const reset=async()=>{if(!selected)return;const password=window.prompt(`New password for ${selected.display_name} (8+ characters)`);if(password){try{await api.resetLearner(selected.id,password);setNotice("Password reset successfully.")}catch(x){setNotice(x instanceof Error?x.message:"Could not reset password")}}};
  const save=async()=>{if(selected){setReward(await api.saveReward(selected.id,reward));setNotice("Reward goal saved.");await refresh()}};
  const generateWorksheet=async()=>{const topic=topics.find(item=>`${item.subject}:${item.id}`===topicKey);if(!topic)return;setGenerating(true);try{const blob=await api.createWorksheet(topic.subject,topic.id,questionCount);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`rabbit-${topic.title.toLowerCase().replaceAll(" ","-")}-${questionCount}-questions.pdf`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setNotice("Worksheet and answer key downloaded.")}catch(error){setNotice(error instanceof Error?error.message:"Could not generate the worksheet")}finally{setGenerating(false)}};
  return <main className="portal-page"><header className="portal-hero"><div><p className="eyebrow">Family dashboard</p><h1>Learning grows here.</h1><p>Create learner profiles, notice strengths, and offer a little extra support where the evidence points.</p></div>{learners.length>0&&<label className="child-picker">Viewing<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{learners.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label>}</header>{notice&&<p className="notice">{notice}</p>}
    <section className="metric-grid"><article><span>Questions tried</span><strong>{progress?.attempts??0}</strong><small>across saved practice</small></article><article><span>Accuracy</span><strong>{Math.round((progress?.accuracy??0)*100)}%</strong><small>{progress?.correct??0} correct answers</small></article><article><span>Hints used</span><strong>{progress?.hints_used??0}</strong><small>a useful practice signal</small></article></section>
    <div className="portal-grid"><section className="panel"><h2>Add a learner</h2><form className="stack-form" onSubmit={create}><label>Child&apos;s display name<input name="name" required/></label><label>Login username<input name="username" minLength={3} required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><button className="primary">Create learner</button></form>{selected&&<button className="quiet reset-link" onClick={reset}>Reset {selected.display_name}&apos;s password</button>}</section>
    <section className="panel"><p className="eyebrow">Learning evidence</p><h2>Practice signals</h2>{progress&&Object.keys(progress.misconceptions).length?<div className="signals">{Object.entries(progress.misconceptions).map(([name,count])=><span key={name}><b>{count}×</b> {name.split(".").slice(-2).join(" ")}</span>)}</div>:<p className="empty">No recurring misconception evidence yet.</p>}</section>
    <section className="panel"><p className="eyebrow">Optional encouragement</p><h2>Accuracy reward</h2><label className="check"><input type="checkbox" checked={reward.enabled} onChange={e=>setReward({...reward,enabled:e.target.checked})}/> Enable a family reward</label><label>Target accuracy (%)<input type="number" min="50" max="100" disabled={!reward.enabled} value={reward.target_accuracy} onChange={e=>setReward({...reward,target_accuracy:Number(e.target.value)})}/></label><label>Present or experience<input disabled={!reward.enabled} maxLength={80} value={reward.reward} onChange={e=>setReward({...reward,reward:e.target.value})}/></label><button className="primary full" disabled={!selected} onClick={save}>Save goal</button></section>
    <section className="panel worksheet-panel"><p className="eyebrow">Practice away from the screen</p><h2>Make a worksheet</h2><p className="empty">Choose a topic and number of questions. The PDF includes a separate answer key with worked explanations.</p><div className="worksheet-fields"><label>Topic<select value={topicKey} onChange={e=>setTopicKey(e.target.value)}>{topics.map(topic=><option value={`${topic.subject}:${topic.id}`} key={`${topic.subject}:${topic.id}`}>{topic.subject_title} · {topic.title}</option>)}</select></label><label>Questions<input type="number" min="1" max="50" value={questionCount} onChange={e=>setQuestionCount(Math.max(1,Math.min(50,Number(e.target.value))))}/></label></div><button className="primary full" disabled={!topicKey||generating} onClick={generateWorksheet}>{generating?"Building PDF…":"Download PDF"}</button></section></div>
    {selected && <AttemptHistory attempts={progress?.attempt_history ?? []} title={`${selected.display_name}'s full question history`} />}
  </main>;
}
