export type ContentBlock = { type: "text" | "math"; value: string };
export type Choice = { id: string; value: string };
export type Question = {
  id: string;
  template_id: string;
  skill: string;
  difficulty: number;
  prompt: ContentBlock[];
  choices: Choice[];
  hint: string;
  visual?: { type: "fraction-bar"; numerator: number; denominator: number; alt: string } | null;
};
export type Session = { id: string; learner_id: string; questions: Question[] };
export type AttemptResult = {
  correct: boolean;
  correct_choice_id: string;
  feedback: string;
  explanation: string;
  misconception_id?: string | null;
  points_earned: number;
};
export type Reward = { enabled: boolean; target_accuracy: number; reward: string };
export type Progress = {
  learner_id: string;
  attempts: number;
  correct: number;
  points: number;
  accuracy: number;
  hints_used: number;
  misconceptions: Record<string, number>;
  recent_attempts: AttemptHistoryItem[];
  attempt_history: AttemptHistoryItem[];
  reward: Reward;
};
export type AttemptHistoryItem = {
  question_id: string;
  skill: string;
  selected_value: string;
  correct_value: string;
  correct: boolean;
  hint_used: boolean;
  misconception_id?: string;
  answered_at: string;
  time_spent_ms: number;
  question: Question;
};
export type User = { id: string; role: "admin" | "parent" | "learner"; username: string; display_name: string; parent_id?: string | null };
export type AuthSession = { access_token: string; expires_at: number; user: User };
export type FamilyLearner = User & { progress: Progress };
export type ImportError = { path: string; message: string; suggestion: string };
export type FamilyProgress = { family_id: string; learners: Array<{ id: string; name: string; progress: Progress }> };
export type Subject = { id: string; title: string; template_count: number; publication_status: "draft" | "published" };
export type WorksheetTopic = { subject: string; subject_title: string; id: string; title: string };

export type DemoSubject = "math" | "trivia" | "english" | "canadian-citizenship";
export type DemoQuestion = {
  id: string;
  subject: DemoSubject;
  kind: "single-select" | "multi-select" | "fill-blank" | "reorder" | "correction";
  title: string;
  instruction: string;
  visual?: "triangle" | "prism";
  latex?: string;
  image?: string;
  image_alt?: string;
  placeholder?: string;
  choices?: Array<{ id: string; label: string }>;
  tiles?: Array<{ id: string; label: string }>;
};
export type DemoSession = { id: string; questions: DemoQuestion[] };
export type DemoResult = { correct: boolean; feedback: string; points_earned: number };
